### ISSUE TITLE
Week 2 Tasks

### ISSUE THREAD

**Issue by WaielonH** [UBC-MDS/cervical-cancer-predictor#9] opened 2022-11-21 21:53 UTC
- 1. Script for setup: @revathyponn 
- 2. Script for EDA: @WaielonH 
- 3. Script for Analysis: @morrismanfung 
- 4. Jupyter Notebook w/ narrative: @samson-bakos EDIT: also code refactoring/ editing 

tasks 1. and 2. to be done before Lab.

detailed plan for analysis/modelling/tuning to be done during lab time.

**Comment by morrismanfung** [comment] 2022-11-22 00:49
I would like to suggest the following:

- From now on, all new branches' name will start with the prefix mx- (e.g. m2-) to show that that branch is created / for Milestone x.
- Stratified splitting should be use in train-test split and cross-validation.
- An environment file with the dependencies should be created.

**Comment by morrismanfung** [comment] 2022-11-22 23:49
**Some Short Comments on [Machine Learning Results](https://github.com/UBC-MDS/cervical-cancer-group7/tree/m2-machine-learning-draft)** (Corresponding commit: #ac87658)

**_Feature Selection and Preprocessing_**

When both binary and numeric columns for the same feature exist, only use 1 of them.

Only 1 STD feature (STDs:condylomatosis) is included as others are too imbalanced.

For numeric features, missing values are imputed with their medians. For binary features, as @WaielonH suggested, missing values will be coded as a new category (thus one-hot encoder is used).

All the selections right now are tentative and subject to change.

**_Model Performance_**

While 13.49% of the observations are labelled as positive, a minimum precision of 14% should be achieved.

KNN: Very poor performance. Decision function is not accessible. No need to further explore this.

SVC: Not bad.

RFC: Not as good as SVC.

Naive Bayes: Not bad.

Logistic Regression: Similar to naive Bayes.

While it is hard to determine the sweet point on the precision-recall curve, maybe we can fix a required precision score so that we can compare the model's recall score on the same basis? For example, using 28% precision as the minimum precision so that when a subject is predicted as with cervical cancer, their posterior probability of having cancer is doubled (from 14% to 28%).

_I am not sure whether the logic above is valid in the case of machine learning as probability can be misleading in this context._

**Comment by samson-bakos** [comment] 2022-11-23 01:04
Well done Morris! Setting a minimum precision or f1 score seems reasonable to me. I understand your logic that the absolute minimum is 13.49%, which would effectively be a dummy classifier that marks everyone as positive, and I believe your posterior probability logic holds as well(?). We can discuss exactly where our operating point should be as we may be able to visually/heuristically determine it via the curves.

As a note for finalizing this, it may be nice to pass a scoring_metrics list similar to our 573 labs instead of independent cross validations, and collate the results in a single table, but that's absolutely something that can be done in final editing (I'll deal with it when constructing the narrative).

**Comment by samson-bakos** [comment] 2022-11-23 16:58
A possible simplification for our initial model search I found on LinkedIn https://pypi.org/project/lazypredict/

Can test multiple algorithms in a single call, we can assess overall model validity based on f1 score, and then optimize the selected model for recall

**Comment by morrismanfung** [comment] 2022-11-24 22:54
@WaielonH, I cannot create the EDA charts and `std_corr.csv` with the script `eda_figures.py` on the main branch. I believe the former is due to altair and can be resolved with Joel's function on slack. Could you change that and check why I cannot save the .csv file?

**Closed as completed** 2022-11-30 23:00 UTC
